import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import {
  knowledgeIngestTool,
  knowledgeSearchTool,
  knowledgeDeleteTool,
} from '../knowledge-tools.js';
import { initKnowledgeIndex } from '../../memory/index.js';

// ── Fixed corpus ────────────────────────────────────────────────────────────

const SHORT_CONTENT =
  'PostgreSQL uses MVCC (Multi-Version Concurrency Control) to handle concurrent ' +
  'transactions without locking. Each transaction sees a consistent snapshot of ' +
  'the database. Write operations create new row versions rather than overwriting ' +
  'existing ones. This allows readers and writers to proceed concurrently without ' +
  'blocking each other, which is fundamental to PostgreSQL performance.';

const LONG_CONTENT =
  'Vector databases are purpose-built storage systems optimised for high-dimensional ' +
  'vector data. They enable semantic search by storing embedding vectors alongside ' +
  'metadata and supporting efficient approximate nearest neighbour (ANN) queries.\n\n' +
  'Traditional databases store structured data in rows and columns. Querying them ' +
  'requires exact matches or range comparisons. Vector databases instead compare ' +
  'the geometric similarity of floating-point vectors, making them ideal for ' +
  'machine learning applications.\n\n' +
  'Embedding models convert raw data — text, images, audio — into dense numeric ' +
  'vectors. These vectors capture semantic meaning: similar concepts end up close ' +
  'together in the vector space. For example, the embeddings for "king" and "queen" ' +
  'are geometrically closer to each other than either is to "bicycle".\n\n' +
  'Approximate nearest neighbour algorithms like HNSW and IVFFlat trade a small ' +
  'degree of accuracy for dramatic speed improvements. For production workloads ' +
  'with millions of vectors, exact exhaustive search would be impractically slow.\n\n' +
  'pgvector is a PostgreSQL extension that adds native vector storage and ANN ' +
  'search. It supports cosine distance, L2 distance, and inner product similarity. ' +
  'Cosine similarity is typically preferred for text embeddings because it measures ' +
  'angular distance rather than magnitude, making it robust to documents of ' +
  'varying length.';

const TAGGED_CONTENT =
  'Cosine similarity measures the angle between two vectors in a high-dimensional ' +
  'space. The result ranges from -1 to 1, where 1 means identical direction, ' +
  '0 means orthogonal, and -1 means opposite directions. For text embeddings ' +
  'generated by models like text-embedding-3-small, values are typically ' +
  'non-negative, ranging from 0 to 1.';

// ── Shared state ─────────────────────────────────────────────────────────────

let shortDocId: string;
let longDocId: string;
let taggedDocId: string;
const allMaterialIds: string[] = [];

function trackId(id: string): string {
  allMaterialIds.push(id);
  return id;
}

// ── Lifecycle ────────────────────────────────────────────────────────────────

beforeAll(async () => {
  await initKnowledgeIndex();

  const [shortResult, longResult, taggedResult] = await Promise.all([
    knowledgeIngestTool.execute!({ title: 'MVCC in PostgreSQL', content: SHORT_CONTENT }, {}),
    knowledgeIngestTool.execute!(
      { title: 'Vector Databases and Semantic Search', content: LONG_CONTENT },
      {}
    ),
    knowledgeIngestTool.execute!(
      {
        title: 'Cosine Similarity Basics',
        content: TAGGED_CONTENT,
        source: 'test-suite',
        tags: ['test', 'rag'],
      },
      {}
    ),
  ]);

  shortDocId = trackId(shortResult.materialId);
  longDocId = trackId(longResult.materialId);
  taggedDocId = trackId(taggedResult.materialId);
});

afterAll(async () => {
  await Promise.all(
    allMaterialIds.map((id) => knowledgeDeleteTool.execute!({ materialId: id }, {}))
  );
});

// ── Ingest tests ─────────────────────────────────────────────────────────────

describe('ingest', () => {
  it('I-1: returns correct output shape', () => {
    expect(shortDocId).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
  });

  it('I-2: short doc (<1000 chars) produces exactly 1 chunk', async () => {
    const result = await knowledgeIngestTool.execute!(
      { title: 'MVCC in PostgreSQL', content: SHORT_CONTENT },
      {}
    );
    trackId(result.materialId);
    expect(result.chunksCreated).toBe(1);
    expect(result.title).toBe('MVCC in PostgreSQL');
  });

  it('I-3: long doc (>2500 chars) produces multiple chunks', async () => {
    const result = await knowledgeIngestTool.execute!(
      { title: 'Vector Databases and Semantic Search', content: LONG_CONTENT },
      {}
    );
    trackId(result.materialId);
    expect(result.chunksCreated).toBeGreaterThan(1);
  });

  it('I-4: source metadata is stored and returned on search', async () => {
    const { results } = await knowledgeSearchTool.execute!(
      { query: 'cosine similarity basics', topK: 3, filterSource: 'test-suite' },
      {}
    );
    expect(results.length).toBeGreaterThan(0);
    results.forEach((r) => expect(r.source).toBe('test-suite'));
  });

  it('I-5: tags metadata is stored and returned on search', async () => {
    const { results } = await knowledgeSearchTool.execute!(
      { query: 'cosine similarity angle vector', topK: 3, filterTags: ['test', 'rag'] },
      {}
    );
    expect(results.length).toBeGreaterThan(0);
    results.forEach((r) => {
      expect(r.tags).toContain('test');
      expect(r.tags).toContain('rag');
    });
  });
});

// ── Search quality ─────────────────────────────────────────────────────────────

describe('search quality', () => {
  it('I-6: search with no matching content returns empty results without error', async () => {
    const { results, totalFound } = await knowledgeSearchTool.execute!(
      { query: 'quantum entanglement superconductors' },
      {}
    );
    expect(Array.isArray(results)).toBe(true);
    expect(totalFound).toBeGreaterThanOrEqual(0);
  });

  it('I-7: top result score for a highly relevant query is >= 0.5', async () => {
    const { results } = await knowledgeSearchTool.execute!(
      { query: 'MVCC concurrency control PostgreSQL', topK: 1 },
      {}
    );
    expect(results.length).toBeGreaterThan(0);
    expect(results[0].score).toBeGreaterThanOrEqual(0.5);
  });

  it('I-8: search after delete returns zero results for that materialId', async () => {
    const { materialId } = await knowledgeIngestTool.execute!(
      { title: 'Temp Delete Test', content: 'Unique ephemeral content for deletion test case.' },
      {}
    );

    await knowledgeDeleteTool.execute!({ materialId }, {});

    const { results } = await knowledgeSearchTool.execute!(
      { query: 'Unique ephemeral content deletion', topK: 5 },
      {}
    );
    const stillPresent = results.filter((r) => r.materialId === materialId);
    expect(stillPresent).toHaveLength(0);
  });

  it('I-9: filterTags with a non-existent tag returns empty results', async () => {
    const { results, totalFound } = await knowledgeSearchTool.execute!(
      { query: 'vector database', topK: 5, filterTags: ['nonexistent-tag-xyz'] },
      {}
    );
    expect(results).toHaveLength(0);
    expect(totalFound).toBe(0);
  });
});
